# Generated by Django 3.2.9 on 2021-12-22 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='The name of the model to which this view applies', max_length=50, verbose_name='model name')),
                ('name', models.CharField(help_text='The name of the search', max_length=50, verbose_name='name')),
                ('is_default', models.BooleanField(default=False, help_text='If this is a default')),
                ('modified', models.DateTimeField(auto_now=True, help_text='The date this search was saved')),
                ('filterstring', models.TextField(blank=True, help_text='The filter string')),
                ('sortstring', models.CharField(blank=True, help_text='The sort string', max_length=100)),
                ('fieldlist', models.CharField(blank=True, help_text='The list of fields to show', max_length=500)),
                ('user', models.ForeignKey(help_text='The user of this search', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['modified'],
            },
        ),
        migrations.AddConstraint(
            model_name='vista',
            constraint=models.UniqueConstraint(fields=('user', 'model_name', 'name'), name='unique_vista'),
        ),
    ]
