# Generated by Django 3.2.9 on 2021-12-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_vistas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vista',
            old_name='fieldlist',
            new_name='shown_fields',
        ),
    ]
