# Generated by Django 3.2.9 on 2021-12-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_vistas', '0004_rename_common_text_search_vista_combined_text_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vista',
            old_name='shown_fields',
            new_name='show_columns',
        ),
    ]
