# Generated by Django 3.2.9 on 2022-01-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_vistas', '0005_rename_shown_fields_vista_show_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='vista',
            name='combined_text_fields',
            field=models.TextField(blank=True, help_text='The list of fields to use for the combined_text_search'),
        ),
    ]
