# Generated by Django 3.2.9 on 2022-02-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_vistas', '0006_vista_combined_text_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vista',
            name='is_global_default',
            field=models.BooleanField(default=0, help_text='If this is search is shared. 0 means no.  After that the highest number is the defacto defalt and others are not.  This should be set by admin'),
        ),
    ]
