# Generated by Django 3.2.9 on 2022-02-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_vistas', '0007_vista_is_global_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vista',
            options={'ordering': ['modified', 'user', 'is_default', 'is_global_default']},
        ),
    ]
