# Generated by Django 4.2.4 on 2023-08-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tougshire_vistas', '0008_alter_vista_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vista',
            options={'ordering': ['modified', 'user', 'name']},
        ),
        migrations.RemoveField(
            model_name='vista',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='vista',
            name='is_global_default',
        ),
    ]
